### ISSUE TITLE
Add some cool hover effect over Navigation items. 

### ISSUE THREAD

**Issue by ankman007** [ankman007/Movie-Website-#3]
### Screenshot
![qtt](https://github.com/ankman007/Movie-Website-/assets/108212023/51da52e0-1b80-4a27-958b-923b3a90e16b)

**Comment by khushalmajoka** [comment]
Please add "hacktoberfest-accepted" label, i will do the needful to solve the issue.

**Comment by ankman007** [comment]
> Please add "hacktoberfest-accepted" label, i will do the needful to solve the issue.

Done

**Comment by khushalmajoka** [comment]
Thanks @ankman007 🎉

**Comment by khushalmajoka** [comment]
Is this good?


https://github.com/ankman007/Movie-Website-/assets/56840292/4ab59a6f-a932-4fd5-9b02-6624f9db93e9
